### ISSUE TITLE
export interfaces in mod.ts

### ISSUE THREAD

**Issue by closet6** [anuragvohraec/compass#1]
im trying to use the interfaces you have defined in compass.ts, but they're not exported in mod.ts.  could you add those or kindly advise a different way?

trying something like this:

`private path: PathDirection | undefined = undefined;
`
...

```
  connectedCallback() {
    super.connectedCallback();

    for (const route of this.routes) {
      this.compass.define(route);
    }
    globalThis.window.addEventListener("hashchange", this._hashHandler, false);
    location.hash = "home";
  }

  private _hashHandler = () => {
    const cObj = this.compass.find(globalThis.location.hash);
    if (cObj) {
      this.path = cObj;
    }
  };
```

**Comment by anuragvohraec** [comment]
> im trying to use the interfaces you have defined in compass.ts, but they're not exported in mod.ts. could you add those or kindly advise a different way?
> 
> trying something like this:
> 
> `private path: PathDirection | undefined = undefined; `
> ...
> 
> ```
>   connectedCallback() {
>     super.connectedCallback();
> 
>     for (const route of this.routes) {
>       this.compass.define(route);
>     }
>     globalThis.window.addEventListener("hashchange", this._hashHandler, false);
>     location.hash = "home";
>   }
> 
>   private _hashHandler = () => {
>     const cObj = this.compass.find(globalThis.location.hash);
>     if (cObj) {
>       this.path = cObj;
>     }
>   };
> ```

Hi There,

I have modified the mod.ts from:
![image](https://user-images.githubusercontent.com/53807480/113222970-c65a5500-92a5-11eb-8ab4-75d3c0507625.png)

to
![image](https://user-images.githubusercontent.com/53807480/113222990-d3774400-92a5-11eb-8c4b-2c7100d60ac7.png)


Try now and let me know.

**Comment by closet6** [comment]
just tried this: 

```
export {
  Compass,
  PathDirection,
} from "https://deno.land/x/compass@1.06/mod.ts";
```

got this: 
```
devdude@f917903617f2:~$ deno bundle --unstable --watch ./src/static/js/mod.ts ./src/static/js/mod.js
Bundle file:///home/devdude/src/static/js/mod.ts
Download https://deno.land/x/compass@1.06/mod.ts
error: Import 'https://deno.land/x/compass@1.06/mod.ts' failed: 404 Not Found
```

please advise, thx

**Comment by anuragvohraec** [comment]
> just tried this:
> 
> ```
> export {
>   Compass,
>   PathDirection,
> } from "https://deno.land/x/compass@1.06/mod.ts";
> ```
> 
> got this:
> 
> ```
> devdude@f917903617f2:~$ deno bundle --unstable --watch ./src/static/js/mod.ts ./src/static/js/mod.js
> Bundle file:///home/devdude/src/static/js/mod.ts
> Download https://deno.land/x/compass@1.06/mod.ts
> error: Import 'https://deno.land/x/compass@1.06/mod.ts' failed: 404 Not Found
> ```
> 
> please advise, thx

Use this url : `https://deno.land/x/compass@v1.06/mod.ts`
You have used `https://deno.land/x/compass@1.06/mod.ts` the one without v in `version`.
The new version is v1.06 (For some reason Git hub was not letting me release code without that 'v'!)

**Comment by closet6** [comment]
ok, thx

```
export { Compass } from "https://deno.land/x/compass@v1.06/mod.ts";
export type { PathDirection } from "https://deno.land/x/compass@v1.06/mod.ts";
```

and this:

`import { Compass, PathDirection } from "./deps.ts";`

worked
